// A deliberately bounded, non-eval formula interpreter for the teaching playground.
export const supportedFunctions=['SUM','AVERAGE','MIN','MAX','COUNT','COUNTA','ROUND','ROUNDUP','ROUNDDOWN','ABS','MOD','SUMPRODUCT','IF','IFS','AND','OR','NOT','IFERROR','COUNTIF','COUNTIFS','SUMIF','SUMIFS','AVERAGEIF','AVERAGEIFS','XLOOKUP','VLOOKUP','HLOOKUP','INDEX','MATCH','XMATCH','LEFT','RIGHT','MID','LEN','TRIM','CLEAN','UPPER','LOWER','PROPER','CONCAT','TEXTJOIN','SUBSTITUTE','VALUE','DATE','DAY','MONTH','YEAR','EDATE','EOMONTH'];
class FormulaError extends Error { constructor(message){super(message);this.name='FormulaError'} }
const fail=(s)=>{throw new FormulaError(s)};
const mapUnary=(x,fn)=>Array.isArray(x)?x.map(v=>mapUnary(v,fn)):fn(x);
const mapBinary=(a,b,fn)=>{if(!Array.isArray(a)&&!Array.isArray(b))return fn(a,b);if(Array.isArray(a)&&Array.isArray(b)){if(a.length!==b.length)fail('#VALUE! — ukuran array berbeda');return a.map((v,i)=>mapBinary(v,b[i],fn))}return Array.isArray(a)?a.map(v=>mapBinary(v,b,fn)):b.map(v=>mapBinary(a,v,fn))};
const logical=x=>{x=scalar(x);if(x==null||x==='')return false;if(typeof x==='string'){if(x.toUpperCase()==='TRUE')return true;if(x.toUpperCase()==='FALSE')return false;fail('#VALUE! — kondisi bukan boolean atau angka')}return Boolean(x)};
const arities={SUM:[1,255],AVERAGE:[1,255],MIN:[1,255],MAX:[1,255],COUNT:[1,255],COUNTA:[1,255],ROUND:[2,2],ROUNDUP:[2,2],ROUNDDOWN:[2,2],ABS:[1,1],MOD:[2,2],SUMPRODUCT:[1,255],IF:[2,3],IFS:[2,254],AND:[1,255],OR:[1,255],NOT:[1,1],IFERROR:[2,2],COUNTIF:[2,2],COUNTIFS:[2,254],SUMIF:[2,3],SUMIFS:[3,255],AVERAGEIF:[2,3],AVERAGEIFS:[3,255],XLOOKUP:[3,6],VLOOKUP:[4,4],HLOOKUP:[4,4],INDEX:[2,3],MATCH:[3,3],XMATCH:[2,3],LEFT:[1,2],RIGHT:[1,2],MID:[3,3],LEN:[1,1],TRIM:[1,1],CLEAN:[1,1],UPPER:[1,1],LOWER:[1,1],PROPER:[1,1],CONCAT:[1,255],TEXTJOIN:[3,255],SUBSTITUTE:[3,4],VALUE:[1,1],DATE:[3,3],DAY:[1,1],MONTH:[1,1],YEAR:[1,1],EDATE:[2,2],EOMONTH:[2,2]};
const scalar=x=>Array.isArray(x)?scalar(x[0]):x;
const flat=x=>[x].flat(Infinity);
const number=x=>{x=scalar(x);if(x===''||x==null)return 0;if(typeof x==='boolean')return +x;const n=Number(x);if(!Number.isFinite(n))fail('#VALUE! — nilai bukan angka');return n};
const txt=x=>{x=scalar(x);return x==null?'':String(x)};
const isNum=x=>typeof x==='number'&&Number.isFinite(x);
const compare=(a,b)=>{a=scalar(a);b=scalar(b);if(typeof a==='string'&&typeof b==='string'){a=a.toLowerCase();b=b.toLowerCase()}return a===b?0:a>b?1:-1};
export function columnName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function cellParts(s){const m=s.replaceAll('$','').match(/^([A-Z]+)(\d+)$/i);if(!m)fail('#REF!');let c=0;for(const ch of m[1].toUpperCase())c=c*26+ch.charCodeAt(0)-64;return [c-1,Number(m[2])-1]}
function lex(s){const tokens=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}let m=s.slice(i).match(/^(?:'(?:[^']|'')+'|[A-Za-z_][A-Za-z0-9_ ]*)!\$?[A-Za-z]{1,3}\$?[1-9]\d*/);if(m){tokens.push({t:'ref',v:m[0]});i+=m[0].length;continue}m=s.slice(i).match(/^\$?[A-Za-z]{1,3}\$?[1-9]\d*\b/);if(m){tokens.push({t:'ref',v:m[0]});i+=m[0].length;continue}if(s[i]==='"'){let value='';i++;let closed=false;while(i<s.length){if(s[i]==='"'){if(s[i+1]==='"'){value+='"';i+=2}else{i++;closed=true;break}}else value+=s[i++]}if(!closed)fail('Tanda kutip belum ditutup');tokens.push({t:'literal',v:value});continue}m=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?/i);if(m){tokens.push({t:'literal',v:Number(m[0])});i+=m[0].length;continue}m=s.slice(i).match(/^[A-Za-z_][A-Za-z0-9_.]*/);if(m){tokens.push({t:'name',v:m[0].toUpperCase()});i+=m[0].length;continue}m=s.slice(i).match(/^(>=|<=|<>|[+\-*/^&=<>%,;():])/);if(m){tokens.push({t:'op',v:m[0]===';'?',':m[0]});i+=m[0].length;continue}fail('Karakter atau sintaks ini belum didukung: '+s[i])}return tokens}
function parse(s){const t=lex(s);let p=0;const peek=()=>t[p]?.v;const take=v=>{if(peek()!==v)fail('Diharapkan '+v);p++};const prec={'=':1,'<>':1,'<':1,'>':1,'<=':1,'>=':1,'&':2,'+':3,'-':3,'*':4,'/':4,'^':5};let nesting=0;function expr(min=0){if(++nesting>80)fail('Formula terlalu dalam');let n,token=t[p++];if(!token)fail('Formula belum lengkap');if(token.t==='literal')n={type:'literal',v:token.v};else if(token.t==='ref'){n={type:'ref',v:token.v};if(peek()===':'){p++;const end=t[p++];if(end?.t!=='ref')fail('Akhir range tidak valid');n={type:'range',a:token.v,b:end.v}}}else if(token.t==='name'){if(token.v==='TRUE'||token.v==='FALSE')n={type:'literal',v:token.v==='TRUE'};else{take('(');let args=[];if(peek()!==')'){do{if(peek()===',')fail('Argumen kosong belum didukung');args.push(expr());if(peek()!==',')break;p++}while(true)}take(')');n={type:'call',name:token.v,args}}}else if(token.v==='('){n=expr();take(')')}else if(token.v==='-'||token.v==='+'){n={type:'unary',op:token.v,node:expr(6)}}else fail('Formula tidak valid');while(peek()==='%'){p++;n={type:'percent',node:n}}while(prec[peek()]>=min){const op=t[p++].v;const rhs=expr(prec[op]+1);n={type:'binary',op,a:n,b:rhs}}nesting--;return n}const node=expr();if(p!==t.length)fail('Ada argumen/simbol yang belum terbaca');return node}
function criteriaMatch(v,crit){if(typeof crit!=='string')return compare(v,crit)===0;let m=crit.match(/^(<=|>=|<>|=|<|>)(.*)$/);let op=m?.[1]||'=',c=m?m[2]:crit;const isPercent=/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)%$/.test(c.trim());if(isPercent)c=String(Number(c.trim().slice(0,-1))/100);const numeric=c.trim()!==''&&Number.isFinite(Number(c));if(numeric){if(typeof v==='string'&&v!==''&&Number.isFinite(Number(v)))v=Number(v);c=Number(c)}else if((op==='='||op==='<>')&&/[?*~]/.test(c)){let pattern='';for(let i=0;i<c.length;i++){const ch=c[i];if(ch==='~'&&i+1<c.length)pattern+=c[++i].replace(/[.*+?^${}()|[\]\\]/g,'\\$&');else if(ch==='*')pattern+='.*';else if(ch==='?')pattern+='.';else pattern+=ch.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}const yes=new RegExp('^'+pattern+'$','i').test(txt(v));return op==='='?yes:!yes}const cmp=compare(v==null?'':v,c);return {'=':cmp===0,'<>':cmp!==0,'>':cmp>0,'<':cmp<0,'>=':cmp>=0,'<=':cmp<=0}[op]}
const serial=d=>(d.getTime()-Date.UTC(1899,11,30))/86400000;
const dateObj=n=>new Date(Date.UTC(1899,11,30)+number(n)*86400000);
export function evaluate(formula,cells={},sheet='Sheet1'){
 const canonical=Object.fromEntries(Object.entries(cells).map(([key,value])=>{const at=key.lastIndexOf('!');return [at<0?key.toUpperCase():key.slice(0,at).toLowerCase()+'!'+key.slice(at+1).toUpperCase(),value]}));const knownSheets=new Set(Object.keys(canonical).filter(k=>k.includes('!')).map(k=>k.slice(0,k.lastIndexOf('!'))));knownSheets.add(sheet.toLowerCase());const used=new Set(),active=new Set();let work=0;const bump=()=>{if(++work>200000)fail('Batas kalkulasi playground terlampaui')};
 const splitRef=(ref,defaultSheet)=>{const idx=ref.lastIndexOf('!');return idx<0?[defaultSheet,ref.replaceAll('$','').toUpperCase()]:[ref.slice(0,idx).replace(/^'|'$/g,'').replaceAll("''","'"),ref.slice(idx+1).replaceAll('$','').toUpperCase()]};
 const get=(ref,defaultSheet)=>{bump();const [sh,addr]=splitRef(ref,defaultSheet);if(!knownSheets.has(sh.toLowerCase()))fail('#REF! — sheet tidak ditemukan');const key=sh.toLowerCase()+'!'+addr;if(active.has(key))fail('#CIRC! — referensi melingkar');let raw;if(Object.prototype.hasOwnProperty.call(canonical,key))raw=canonical[key];else if(sh.toLowerCase()===sheet.toLowerCase()&&Object.prototype.hasOwnProperty.call(canonical,addr))raw=canonical[addr];else raw='';if(typeof raw==='string'&&raw.startsWith('=')){if(active.size>60)fail('Referensi terlalu dalam');active.add(key);try{return run(parse(raw.slice(1)),sh)}finally{active.delete(key)}}return raw??''};
 function run(n,sh){bump();if(n.type==='literal')return n.v;if(n.type==='ref')return get(n.v,sh);if(n.type==='range'){const [sheetA,a]=splitRef(n.a,sh),[sheetB,b]=splitRef(n.b,sheetA);if(sheetA.toLowerCase()!==sheetB.toLowerCase())fail('Range lintas sheet tidak didukung');const [ac,ar]=cellParts(a),[bc,br]=cellParts(b);if(bc<ac||br<ar||(bc-ac+1)*(br-ar+1)>25000)fail('Range tidak valid atau terlalu besar');const rows=[];for(let r=ar;r<=br;r++){const row=[];for(let c=ac;c<=bc;c++)row.push(get(sheetA+'!'+columnName(c)+(r+1),sheetA));rows.push(row)}return rows}if(n.type==='unary')return mapUnary(run(n.node,sh),x=>(n.op==='-'?-1:1)*number(x));if(n.type==='percent')return mapUnary(run(n.node,sh),x=>number(x)/100);if(n.type==='binary'){const av=run(n.a,sh),bv=run(n.b,sh);return mapBinary(av,bv,(a,b)=>{switch(n.op){case '+':return number(a)+number(b);case '-':return number(a)-number(b);case '*':return number(a)*number(b);case '/':if(number(b)===0)fail('#DIV/0! — pembagi nol');return number(a)/number(b);case '^':return number(a)**number(b);case '&':return txt(a)+txt(b);default:const cmp=compare(a,b);return {'=':cmp===0,'<>':cmp!==0,'>':cmp>0,'<':cmp<0,'>=':cmp>=0,'<=':cmp<=0}[n.op]}})}if(n.type==='call'){const name=n.name;used.add(name);if(!supportedFunctions.includes(name))fail(name+' belum didukung playground. Gunakan Excel untuk formula ini.');const bounds=arities[name];if(bounds&&(n.args.length<bounds[0]||n.args.length>bounds[1]))fail('Jumlah argumen '+name+' tidak valid');const arg=i=>{if(!n.args[i])fail('Argumen '+name+' belum lengkap');return run(n.args[i],sh)};if(name==='IF'){if(n.args.length<2||n.args.length>3)fail('IF memerlukan 2–3 argumen');return logical(arg(0))?arg(1):n.args[2]?arg(2):false}if(name==='IFERROR'){try{return arg(0)}catch(e){return arg(1)}}if(name==='IFS'){for(let i=0;i<n.args.length;i+=2)if(logical(arg(i)))return arg(i+1);fail('#N/A — tidak ada kondisi cocok')}
 const a=n.args.map(x=>run(x,sh)),f=flat(a),nums=['SUM','AVERAGE','MIN','MAX','COUNT'].includes(name)?a.flatMap((v,i)=>{if(n.args[i].type==='ref'||n.args[i].type==='range'||Array.isArray(v))return flat(v).filter(isNum);if(typeof v==='boolean')return [+v];if(typeof v==='string'){if(v.trim()===''||!Number.isFinite(Number(v))){if(name==='COUNT')return [];fail('#VALUE! — argumen teks bukan angka')}return [Number(v)]}return isNum(v)?[v]:[]}):f.filter(isNum),sum=xs=>xs.reduce((s,x)=>s+x,0),num=i=>number(a[i]),str=i=>txt(a[i]);
 switch(name){case 'SUM':return sum(nums);case 'AVERAGE':if(!nums.length)fail('#DIV/0!');return sum(nums)/nums.length;case 'MIN':return nums.length?Math.min(...nums):0;case 'MAX':return nums.length?Math.max(...nums):0;case 'COUNT':return nums.length;case 'COUNTA':return f.filter(x=>x!==''&&x!=null).length;case 'ABS':return Math.abs(num(0));case 'MOD':if(!num(1))fail('#DIV/0!');return num(0)-num(1)*Math.floor(num(0)/num(1));case 'ROUND':case 'ROUNDUP':case 'ROUNDDOWN':{const x=num(0),scale=10**num(1),y=Math.abs(x)*scale;return Math.sign(x)*(name==='ROUND'?Math.floor(y+0.5+Number.EPSILON*y):name==='ROUNDUP'?Math.ceil(y):Math.floor(y))/scale}case 'SUMPRODUCT':{const arrays=a.map(flat);if(!arrays.length||arrays.some(x=>x.length!==arrays[0].length))fail('#VALUE! — ukuran range berbeda');return sum(arrays[0].map((_,i)=>arrays.reduce((p,row)=>p*(isNum(row[i])?row[i]:0),1)))}case 'AND':case 'OR':{const vals=a.flatMap((v,i)=>{if(n.args[i].type==='ref'||n.args[i].type==='range')return flat(v).filter(x=>typeof x==='number'||typeof x==='boolean');return flat(v).map(logical)});if(!vals.length)fail('#VALUE! — tidak ada nilai logis');return name==='AND'?vals.every(Boolean):vals.some(Boolean)}case 'NOT':return !logical(a[0]);
 case 'COUNTIF':case 'SUMIF':case 'AVERAGEIF':case 'COUNTIFS':case 'SUMIFS':case 'AVERAGEIFS':{const plural=name.endsWith('S');let ranges=[],criteria=[],values;if(plural){const offset=name==='COUNTIFS'?0:1;values=offset?flat(a[0]):null;if((a.length-offset)%2!==0||a.length<=offset)fail('Pasangan range/kriteria belum lengkap');for(let i=offset;i<a.length;i+=2){ranges.push(flat(a[i]));criteria.push(scalar(a[i+1]))}}else{if(a.length<2)fail('Kriteria belum lengkap');ranges=[flat(a[0])];criteria=[scalar(a[1])];values=name==='COUNTIF'?null:flat(a[2]??a[0])}const len=ranges[0].length;if(ranges.some(x=>x.length!==len)||(values&&values.length!==len))fail('#VALUE! — ukuran range harus sama');const hits=[];for(let i=0;i<len;i++)if(ranges.every((r,j)=>criteriaMatch(r[i],criteria[j])))hits.push(i);if(name.startsWith('COUNT'))return hits.length;const vals=hits.map(i=>values[i]).filter(isNum);if(name.startsWith('AVERAGE')){if(!vals.length)fail('#DIV/0! — tidak ada angka cocok');return sum(vals)/vals.length}return sum(vals)}
 case 'XLOOKUP':{const keys=flat(a[1]),vals=flat(a[2]);if(keys.length!==vals.length)fail('#VALUE! — range lookup berbeda ukuran');if(a[4]!=null&&number(a[4])!==0)fail('Playground hanya mendukung XLOOKUP exact match (0)');if(a[5]!=null&&number(a[5])!==1)fail('Playground hanya mendukung pencarian pertama (1)');const i=keys.findIndex(x=>compare(x,scalar(a[0]))===0);if(i<0){if(a.length>3)return a[3];fail('#N/A — ID tidak ditemukan')}return vals[i]??0}
 case 'MATCH':case 'XMATCH':{if(a[2]!=null&&num(2)!==0)fail('Playground hanya mendukung exact match (0)');if(name==='MATCH'&&a[2]==null)fail('Gunakan MATCH(...,0) untuk exact match di playground');const i=flat(a[1]).findIndex(x=>compare(x,scalar(a[0]))===0);if(i<0)fail('#N/A');return i+1}
 case 'INDEX':{const table=Array.isArray(a[0])?a[0]:[[a[0]]];const r=num(1)-1,c=a.length>2?num(2)-1:0;if(r<0||c<0||!table[r]||table[r][c]===undefined)fail('#REF!');return table[r][c]}
 case 'VLOOKUP':case 'HLOOKUP':{if(a.length<4||Boolean(scalar(a[3])))fail('Playground mendukung exact match: gunakan FALSE');const table=a[1],index=num(2)-1;if(!Array.isArray(table)||index<0)fail('#VALUE!');if(name==='VLOOKUP'){const row=table.find(r=>compare(r[0],scalar(a[0]))===0);if(!row)fail('#N/A');if(row[index]===undefined)fail('#REF!');return row[index]}const col=table[0].findIndex(v=>compare(v,scalar(a[0]))===0);if(col<0)fail('#N/A');if(!table[index])fail('#REF!');return table[index][col]}
 case 'LEFT':{const len=a.length>1?Math.trunc(num(1)):1;if(len<0)fail('#VALUE! — panjang negatif');return str(0).slice(0,len)}case 'RIGHT':{const len=a.length>1?Math.trunc(num(1)):1;if(len<0)fail('#VALUE! — panjang negatif');return len?str(0).slice(-len):''}case 'MID':if(num(1)<1||num(2)<0)fail('#VALUE!');return str(0).slice(num(1)-1,num(1)-1+num(2));case 'LEN':return str(0).length;case 'TRIM':return str(0).replace(/^ +| +$/g,'').replace(/ +/g,' ');case 'CLEAN':return str(0).replace(/[\x00-\x1f]/g,'');case 'UPPER':return str(0).toUpperCase();case 'LOWER':return str(0).toLowerCase();case 'PROPER':return str(0).toLowerCase().replace(/(^|[^a-z])([a-z])/g,(m,p,c)=>p+c.toUpperCase());case 'CONCAT':return f.map(txt).join('');case 'TEXTJOIN':return flat(a.slice(2)).filter(x=>!a[1]||(x!==''&&x!=null)).map(txt).join(str(0));case 'SUBSTITUTE':{let i=0;const old=str(1);if(!old)return str(0);return str(0).split(old).reduce((out,p,j)=>j?out+((a.length<4||++i===num(3))?str(2):old)+p:p,'')}case 'VALUE':return num(0);case 'DATE':{let y=num(0);if(y>=0&&y<1900)y+=1900;return serial(new Date(Date.UTC(y,num(1)-1,num(2))))}case 'DAY':return dateObj(a[0]).getUTCDate();case 'MONTH':return dateObj(a[0]).getUTCMonth()+1;case 'YEAR':return dateObj(a[0]).getUTCFullYear();case 'EDATE':case 'EOMONTH':{const d=dateObj(a[0]),offset=Math.trunc(num(1));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+offset+1,0));return serial(name==='EOMONTH'?last:new Date(Date.UTC(last.getUTCFullYear(),last.getUTCMonth(),Math.min(d.getUTCDate(),last.getUTCDate()))))}default:fail('Fungsi belum tersedia')}
 }fail('Formula tidak valid')}
 try{if(typeof formula!=='string'||formula.length>4000)fail('Formula terlalu panjang');if(!formula.startsWith('='))fail('Mulai formula dengan tanda =');const value=run(parse(formula.slice(1)),sheet);if(Array.isArray(value))fail('Hasil array/spill belum ditampilkan. Gunakan Excel untuk hasil array.');if(typeof value==='number'&&!Number.isFinite(value))fail('#NUM!');return {value:scalar(value),error:null,usedFunctions:[...used]}}catch(e){return {value:null,error:e instanceof FormulaError?e.message:'Argumen tidak valid atau belum didukung',usedFunctions:[...used]}}
}
export function sameResult(actual,expected,tolerance=0.01){if(typeof expected==='number'){if(actual===''||actual==null||typeof actual==='boolean')return false;return Number.isFinite(Number(actual))&&Math.abs(Number(actual)-expected)<=tolerance}return String(actual??'').trim().toLowerCase()===String(expected).trim().toLowerCase()}
export function formulaFunctions(formula){const clean=String(formula||'').replace(/"(?:[^"]|"")*"/g,'').replace(/'(?:[^']|'')*'/g,'');return [...clean.matchAll(/\b([A-Z_][A-Z0-9_.]*)\s*\(/gi)].map(m=>m[1].toUpperCase().split('.').at(-1))}
